# Generated by Django 5.2 on 2026-05-24 10:03

from django.db import migrations

def migrate_data(apps, schema_editor):
    OldKader = apps.get_model('accounts', 'Kader')
    OldUserProfile = apps.get_model('accounts', 'UserProfile')
    OldDeviceCounter = apps.get_model('accounts', 'DeviceCounter')

    Team = apps.get_model('account', 'Team')
    Profile = apps.get_model('account', 'Profile')
    Device = apps.get_model('account', 'Device')

    # Migrate Kader -> Team
    kader_to_team = {}
    for kader in OldKader.objects.all():
        team = Team.objects.create(
            name=kader.name,
            shared_pool=kader.shared_pool,
        )
        kader_to_team[kader.id] = team

    # Migrate UserProfile -> Profile
    for old_profile in OldUserProfile.objects.select_related('user', 'kader').all():
        team = kader_to_team.get(old_profile.kader_id) if old_profile.kader_id else None
        profile = Profile.objects.create(
            user=old_profile.user,
            active_team=team,
        )
        if team:
            profile.teams.add(team)

    # Migrate DeviceCounter -> Device
    for old_device in OldDeviceCounter.objects.all():
        team = Team.objects.get(name="Nationalkader")
        if team:
            Device.objects.create(
                team=team,
                mobile=old_device.mobile_count,
                desktop=old_device.desktop_count,
            )

class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("accounts", "0003_kader_shared_pool"),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
