# Generated by Django 5.2 on 2026-06-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_forumthread_forumcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumcomment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forumthread",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
