providers = ["python", "node"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm ci --omit=dev"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --no-input",
  "python manage.py migrate"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"
