[build]
builder = "RAILPACK"
buildCommand = "npm install --omit=dev && python manage.py collectstatic --clear --noinput"

[deploy]
preDeployCommand = ["python manage.py migrate"]
startCommand = "chmod +x start.sh && ./start.sh"
