databases:
  - name: db
    plan: free
    databaseName: db
    user: lars

services:
  - type: web
    plan: free
    name: CQCPathfinder
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn CQCPathfinder.wsgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --lifespan off'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
