# Generated by Django 5.2 on 2026-06-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavGraphBuildTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mask_basename", models.CharField(db_index=True, max_length=255)),
                ("mask_width", models.IntegerField(blank=True, null=True)),
                ("mask_height", models.IntegerField(blank=True, null=True)),
                ("n_nodes", models.IntegerField(blank=True, null=True)),
                ("n_edges", models.IntegerField(blank=True, null=True)),
                ("n_components", models.IntegerField(blank=True, null=True)),
                ("main_component_pct", models.FloatField(blank=True, null=True)),
                ("build_seconds", models.FloatField()),
                ("sidecar_bytes", models.BigIntegerField(blank=True, null=True)),
                ("sidecar_version", models.IntegerField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("unet", "After UNet mask generation"),
                            ("rebuild_endpoint", "Editor rebuild endpoint"),
                            ("management", "build_navgraphs management command"),
                            ("lazy", "Lazy build inside query.run"),
                        ],
                        db_index=True,
                        default="lazy",
                        max_length=32,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "NavGraph build timing",
                "verbose_name_plural": "NavGraph build timings",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PathfindingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mask_basename", models.CharField(db_index=True, max_length=255)),
                ("start_x", models.IntegerField()),
                ("start_y", models.IntegerField()),
                ("ziel_x", models.IntegerField()),
                ("ziel_y", models.IntegerField()),
                ("n_routes_requested", models.IntegerField()),
                ("n_routes_returned", models.IntegerField()),
                ("n_existing_routes", models.IntegerField(default=0)),
                ("n_blocked_features", models.IntegerField(default=0)),
                ("query_seconds", models.FloatField()),
                ("success", models.BooleanField(default=True)),
                (
                    "cold",
                    models.BooleanField(
                        default=False,
                        help_text="Suspected first query for this mask in this process.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("editor_button", "Editor: Neue Route button"),
                            ("editor_auto", "Editor: auto_pathfind on CP creation"),
                            ("coursesetter", "Coursesetter (legacy)"),
                            ("batch", "Batch pathfinding"),
                            ("benchmark", "Benchmark management command"),
                            ("unknown", "Unknown / unset"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Pathfinding timing",
                "verbose_name_plural": "Pathfinding timings",
                "ordering": ("-created_at",),
            },
        ),
    ]
