import os
import zipfile
from django.http import StreamingHttpResponse, Http404
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test

# Custom generator class that behaves like a writeable file-like object 
# but yields bytes immediately as zipfile writes them
class ZipStreamWriter:
    def __init__(self):
        self.buffer = b''
    def write(self, data):
        self.buffer += data
    def flush(self):
        pass
    def read_and_clear(self):
        chunk = self.buffer
        self.buffer = b''
        return chunk

def stream_media_zip(media_root):
    stream = ZipStreamWriter()
    
    # Initialize zip archive targeting our custom streaming wrapper
    with zipfile.ZipFile(stream, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        for root, dirs, files in os.walk(media_root):
            for file in files:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, media_root)
                
                try:
                    zip_file.write(file_path, arcname)
                    # Yield data chunks generated by adding this file
                    chunk = stream.read_and_clear()
                    if chunk:
                        yield chunk
                except Exception:
                    continue # Skip unreadable or locked files silently
                    
    # Yield any remaining structural zip footer bytes
    yield stream.read_and_clear()

@user_passes_test(lambda u: u.is_superuser)
def download_media_archive(request):
    media_root = getattr(settings, 'MEDIA_ROOT', '/app/media')

    if not os.path.exists(media_root):
        raise Http404("Media directory not found on production volume.")

    # Wrap generator in StreamingHttpResponse to keep proxy connections alive
    response = StreamingHttpResponse(
        stream_media_zip(media_root),
        content_type='application/zip'
    )
    response['Content-Disposition'] = 'attachment; filename="production_media.zip"'
    
    return response