# Generated by Django 5.2 on 2025-12-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_count", models.PositiveIntegerField(default=0)),
                ("desktop_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
