# Generated by Django 5.2 on 2025-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_devicecounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="kader",
            name="shared_pool",
            field=models.BooleanField(default=False),
        ),
    ]
