# Generated by Django 5.2 on 2026-07-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_kader_shared_pool"),
        ("coursesetter", "0012_delete_publishedfile"),
        ("play", "0007_delete_userresult"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceCounter",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="kader",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Kader",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
