# Generated by Django 5.2 on 2025-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0005_rename_publishedfiles_publishedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedfile",
            name="ncP",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
