# Generated by Django 5.2 on 2025-06-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0006_publishedfile_ncp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publishedfile",
            old_name="ncP",
            new_name="control_point_count",
        ),
    ]
