# Generated by Django 5.2 on 2025-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0006_publishedfile_author_publishedfile_ncp"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedfile",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publishedfile",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
