# Generated by Django 5.2 on 2025-12-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("coursesetter", "0007_publishedfile_data_publishedfile_last_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedfile",
            name="kader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_files",
                to="accounts.kader",
            ),
        ),
    ]