# Generated by Django 5.2 on 2025-06-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0007_rename_ncp_publishedfile_control_point_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publishedfile",
            old_name="control_point_count",
            new_name="ncP",
        ),
    ]
