# Generated by Django 5.2 on 2025-06-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0008_rename_control_point_count_publishedfile_ncp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishedfile",
            name="ncP",
        ),
    ]
