# Generated by Django 5.2 on 2025-06-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0009_remove_publishedfile_ncp"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedfile",
            name="author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="publishedfile",
            name="ncP",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
