# Generated by Django 5.2 on 2025-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0009_auto_20251203_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedfile",
            name="filename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="publishedfile",
            name="unique_filename",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
