# Generated by Django 5.2 on 2026-04-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0010_alter_publishedfile_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedfile",
            name="batch_progress",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
