# Generated by Django 5.2 on 2026-07-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0011_publishedfile_batch_progress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="publishedFile",
        ),
    ]
