# Generated by Django 5.2 on 2025-12-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
    ]
