# Generated by Django 5.2 on 2026-05-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_migrate_data_from_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_pathfind", models.BooleanField(default=False)),
                ("auto_jump", models.BooleanField(default=True)),
                ("autosave", models.BooleanField(default=False)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_settings",
                        to="account.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("published", models.BooleanField(default=False)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("scale", models.FloatField(blank=True, null=True)),
                ("scaled", models.BooleanField(default=False)),
                ("map_file", models.CharField(blank=True, max_length=255)),
                ("has_mask", models.BooleanField(default=False)),
                ("blocked_terrain", models.JSONField(blank=True, null=True)),
                ("last_edited", models.DateTimeField(default=timezone.now)),
                ("batch_progress", models.JSONField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="account.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("ziel", models.JSONField(blank=True, null=True)),
                ("start", models.JSONField(blank=True, null=True)),
                ("complex", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_pairs",
                        to="project.file",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("file", "order")},
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="account.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "team")},
            },
        ),
        migrations.CreateModel(
            name="FileSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trigger", models.CharField(blank=True, max_length=100)),
                ("scale", models.FloatField(blank=True, null=True)),
                ("map_file", models.CharField(blank=True, max_length=255)),
                ("has_mask", models.BooleanField(default=False)),
                ("blocked_terrain", models.JSONField(blank=True, null=True)),
                ("control_pairs", models.JSONField()),
                ("n_control_pairs", models.IntegerField(default=0)),
                ("n_routes", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="project.file",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="project.label",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("name", "team")},
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("rP", models.JSONField(blank=True, null=True)),
                ("noA", models.IntegerField(blank=True, null=True)),
                ("pos", models.FloatField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("run_time", models.FloatField(blank=True, null=True)),
                ("elevation", models.IntegerField(blank=True, null=True)),
                (
                    "control_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="project.controlpair",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("control_pair", "order")},
            },
        ),
    ]
