# Generated by Django 5.2 on 2026-05-24 09:43
# Merged: 0004_file_lock, 0005_label_color, 0006_filesnapshot_name_label_author

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_migrate_data_from_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_pathfind",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("auto_jump", models.BooleanField(default=True)),
                ("auto_obstacle", models.BooleanField(default=True)),
                ("autosave", models.BooleanField(default=False)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_settings",
                        to="account.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#5b8db8", max_length=7)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="account.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "team")},
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("published", models.BooleanField(default=False)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("scale", models.FloatField(blank=True, null=True)),
                ("map_scale", models.PositiveIntegerField(default=4000)),
                ("scaled", models.BooleanField(default=False)),
                ("map_file", models.CharField(blank=True, max_length=255)),
                ("has_mask", models.BooleanField(default=False)),
                ("blocked_terrain", models.JSONField(blank=True, null=True)),
                ("last_edited", models.DateTimeField(default=timezone.now)),
                ("batch_progress", models.JSONField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="project.label",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to="account.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("ziel", models.JSONField(blank=True, null=True)),
                ("start", models.JSONField(blank=True, null=True)),
                ("complex", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_pairs",
                        to="project.file",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("file", "order")},
            },
        ),
        migrations.CreateModel(
            name="FileSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trigger", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("scale", models.FloatField(blank=True, null=True)),
                ("map_scale", models.PositiveIntegerField(default=4000)),
                ("map_file", models.CharField(blank=True, max_length=255)),
                ("has_mask", models.BooleanField(default=False)),
                ("blocked_terrain", models.JSONField(blank=True, null=True)),
                ("control_pairs", models.JSONField()),
                ("n_control_pairs", models.IntegerField(default=0)),
                ("n_routes", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="project.file",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="project.label",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("name", "team")},
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("rP", models.JSONField(blank=True, null=True)),
                ("noA", models.FloatField(blank=True, null=True)),
                ("pos", models.FloatField(blank=True, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("run_time", models.FloatField(blank=True, null=True)),
                ("elevation", models.IntegerField(blank=True, null=True)),
                ("obstacle", models.IntegerField(blank=True, null=True)),
                (
                    "control_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="project.controlpair",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("control_pair", "order")},
                "indexes": [
                    models.Index(
                        fields=["control_pair", "run_time"],
                        name="route_cp_runtime_idx",
                    ),
                ],
            },
        ),
    ]
