# Generated by Django 5.2 on 2026-07-03 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("project", "0003_create_editor_settings_for_existing_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["team", "deleted", "-last_edited"],
                name="file_team_deleted_edited_idx",
            ),
        ),
    ]
