# Generated by Django 5.2 on 2026-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_file_team_deleted_last_edited_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="infinite_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="file",
            name="infinite_region",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
