# Generated by Django 5.2 on 2026-05-26 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_filesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="last_edited",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
