# Generated by Django 5.2 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_file_infinite_enabled_file_infinite_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="level_passages",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filesnapshot",
            name="level_passages",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
