# Generated by Django 5.2 on 2025-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0003_userresult_play_userre_filenam_90fcff_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresult",
            name="competition",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userresult",
            name="selected_route",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
