# Generated by Django 5.2 on 2025-12-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("play", "0004_userresult_competition_userresult_selected_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresult",
            name="kader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_results",
                to="accounts.kader",
            ),
        ),
    ]
