# Generated by Django 5.2 on 2026-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0005_userresult_kader"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresult",
            name="longest_route_runtime",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
