# Generated by Django 5.2 on 2026-07-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0006_userresult_longest_route_runtime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserResult",
        ),
    ]
